apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: kubernetes
  name: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kubernetes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: kubernetes
    spec:
      containers:
      - image: tvadugu/mywebapp:firsttest
        name: kubernetes
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /student-service
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
        resources: {}
status: {}

